### ISSUE TITLE
How to use with RPGMaker MZ?

### ISSUE THREAD

**Issue by wenkokke** [LunaTechsDev/Luna-QPlugins#24]
I understand how to compile and import these plugins:

- build plugins from source or download prebuilt from, e.g., [nightly](https://github.com/LunaTechsDev/Luna-QPlugins/releases/tag/nightly)
- move plugins into plugin directory and import into RPGMaker

However, once I’ve done that, the player is simply unable to move, probably because everything is now a collision.

How do I create and load collision maps?

**Comment by inc0der** [comment]
Hey sorry for such a late reply, I've been really busy but last I tested the nightly plugins they were working as intended. You should not require a collision map for the player to move, it uses the tileset collision set in the MZ database.

**Comment by wenkokke** [comment]
If I use a custom tileset, I’ll end up needing a collision map, though, right?

**Comment by inc0der** [comment]
You will need a collision map if you want to have refined collision with parallax mapping and unique tilesets, yes. To add a collision map image to your map use this notetag inside the map's properties in the notebox 
``` 
<cm:FILENAME>
```

For further information about the QPlugins it's a good idea to get familiar with the original creator's [plugin guides](https://quxios.github.io/plugins) on their website
